=== Sriee/epi/Report/data/config_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema definition for configuring database loading and report generation
            modules.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="config">
        <xs:complexType>
            <xs:all>
                <xs:element name="database">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="machine" type="xs:string"/>
                            <xs:element name="update" type="xs:boolean"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="report">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="output_type" type="xs:string"
                                        minOccurs="0" maxOccurs="1">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="html" />
                                        <xs:enumeration value="json" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="output_file_name" type="xs:string"
                                        minOccurs="0" maxOccurs="1"/>
                            <xs:element name="template" type="xs:string"/>
                            <xs:element name="user" type="xs:string"/>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Sriee/epi/Report/data/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config_schema.xsd">
    <report>
        <output_type>html</output_type>
        <template>production</template>
        <user>tom</user>
    </report>
    <database>
        <machine>dev1</machine>
        <update>true</update>
    </database>
</config>
